defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: Mason Website
subtitle: Digital Fab & Prototyping Fundamentals
baseurl: "/web-pk"  # the subpath of your site, e.g. /blog
# theme: panthera-jekyll
remote-theme: christianezeani/panthera-jekyll

# Side Menu Links
menu:
  - text: Home
    link: /
    icon: ""

  - text: About
    link: /about.html
    icon: ""

  - text: Electronics production
    link: /docs/electronicsprod.html
    icon: ""

  - text: Electronics design
    link: /docs/electronicsdesign.html
    icon: ""

  - text: Embedded programming
    link: /docs/programming.html
    icon: ""

  - text: 2D computer controlled machining
    link: /docs/2Dmachine.html
    icon: ""

  - text: 3D machining
    link: /docs/3Dmachine.html
    icon: ""

  - text: Molding & Casting
    link: /docs/Molding.html
    icon: ""

  - text: Interface & Applications Programming
    link: /docs/Interface.html
    icon: ""

  - text: Introduction to IOT
    link: /docs/IOT.html
    icon: ""
 
  - text: Final project 
    link: /docs/project.html
    icon: ""
 
 - text: Contact
    link: /contact.html
    icon: ""


# Socialmedia Icons
social_icons:
  - name: linkedin
    link: ""
    icon: fab fa-linkedin

  - name: github
    link: ""
    icon: fab fa-github-square

  - name: facebook
    link: ""
    icon: fab fa-facebook-square

  - name: twitter
    link: ""
    icon: fab fa-twitter
